#Dockerfile.test

#Run as
#docker buildx build \
#--platform linux/arm64 \
#-f Dockerfile.test .

FROM kerya/debian:lib-test

COPY libcamera_0.5.2-1_arm64.deb .

RUN meson setup build -Denable_libav=enabled -Denable_drm=enabled -Denable_egl=enabled -Denable_qt=enabled -Denable_opencv=disabled -Denable_tflite=disabled -Denable_hailo=disabled && \
	meson install -C build && \
	meson install -C build && \
	rpicam-still --version && \
	rpicam-hello

