name: Compile for ARM64

# Controls when the workflow will run
on:
  push:
    tags:
      - "v*.*.*"
      
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-22.04-arm
    container: kerya/debian:arm64
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Compile and create DEB package
        run: |
          export USER=root
          export LOGNAME=root
          cd libcamera-0.5.2
          dh_make --createorig --single --yes
          yes | cp -rf ../rules debian/rules
          meson setup obj-aarch64-linux-gnu --buildtype=release --prefix=/usr --sysconfdir=/etc --localstatedir=/var --libdir=/usr/local/lib/aarch64-linux-gnu -Dpipelines=rpi/vc4,rpi/pisp -Dipas=rpi/vc4,rpi/pisp -Dv4l2=true -Dgstreamer=disabled -Dtest=false -Dlc-compliance=disabled -Dcam=disabled -Dqcam=disabled -Ddocumentation=disabled -Dpycamera=enabled
          dpkg-buildpackage -rfakeroot -us -uc -b
          cd ..

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: libcamera_0.5.2-1_arm64.deb
          path: libcamera_0.5.2-1_arm64.deb

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            libcamera_0.5.2-1_arm64.deb
